### ISSUE TITLE
Setting Push session headers

### ISSUE THREAD

**Issue by Fedoms** [brunofarache/liferay-push-android#13]
Hi,
I'm trying to initialize a `Push` object with a session which has some custom headers, but it doesn't seems to work. It's like the headers are ignored in creating the `SessionImpl` inside `Push`.
Is there a way to set custom headers for the `Push` session object??

**Comment by javiergamarra** [comment]
We've released a version (https://github.com/liferay-mobile/liferay-push-android/releases/tag/1.1.1) solving this bug :)

Please reopen if it doesn't solve your use case
